resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/max851/cnc1.git

jobs:
- name: job2
  plan:
  - get: git-repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: git-repo
      run:
        path: cat
        args: ["repo/README.md"]
